<?php

function cfa_invasive_map_init() {
    drupal_add_js('http://maps.googleapis.com/maps/api/js?sensor=false', 'external');
    drupal_add_js(drupal_get_path('module', 'cfa_invasive_map') . '/js/cfa_map.js');
}

/**
 * Implementation of hook_menu().
 */
function cfa_invasive_map_menu() {
  $items = array();

  $items['invasives/map'] = array(
    'title' => 'Page title here',
    'description' => 'Description here, mostly used for admin pages',
    'page callback' => 'cfa_invasive_map_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );
  return $items;
}

function cfa_invasive_map_callback($arg) {//this function generates the page content
  return t('<div id="map-canvas" style="width: 100%; height: 200px;"></div>The arg is @arg', array('@arg' => $arg));
}

